<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="shivprasad-ThinkPad-T460" failures="1" tests="1" name="assertion.Soft_assertion_with_assertAll" time="0.006" errors="0" timestamp="2024-02-01T23:21:04 IST" skipped="0">
  <testcase classname="assertion.Soft_assertion_with_assertAll" name="division" time="0.006">
    <failure message="The following asserts failed:
	!!! =====================Soft Assertio _All: division operation is not valid ===================== expected [5] but found [2],
	!!! =====================Soft Assertio _All: multiply operation is not valid ===================== expected [19] but found [18]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
!!! =====================Soft Assertio _All: division operation is not valid ===================== expected [5] but found [2],
!!! =====================Soft Assertio _All: multiply operation is not valid ===================== expected [19] but found [18]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at assertion.Soft_assertion_with_assertAll.division(Soft_assertion_with_assertAll.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
    </failure>
  </testcase> <!-- division -->
  <system-out/>
</testsuite> <!-- assertion.Soft_assertion_with_assertAll -->
